apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: naughty-egret-go 
  janus-idp.io/tekton: naughty-egret-go
  backstage.io/kubernetes-id: naughty-egret-go
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: naughty-egret-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  