apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: naughty-egret-go
  janus-idp.io/tekton: naughty-egret-go
  backstage.io/kubernetes-id: naughty-egret-go
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: naughty-egret-go
resources: 
- deployment.yaml
- route.yaml
- service.yaml
